import json
import subprocess
import sys
from pathlib import Path

from src.ingest import ingest_repository, write_raw_file_list

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def test_ingests_supported_source_and_readme_files(tmp_path: Path) -> None:
    _write(tmp_path / "src" / "app.py", "def run():\n    return 1\n")
    _write(tmp_path / "web" / "client.js", "function run() {}\n")
    _write(tmp_path / "web" / "types.ts", "export type User = { id: string }\n")
    _write(tmp_path / "java" / "Main.java", "class Main {}\n")
    _write(tmp_path / "README.md", "# Sample\n")
    _write(tmp_path / "docs" / "guide.md", "# Not included\n")

    result = ingest_repository(tmp_path)

    assert {file.filepath for file in result.files} == {
        "README.md",
        "java/Main.java",
        "src/app.py",
        "web/client.js",
        "web/types.ts",
    }


def test_skips_ignored_directories(tmp_path: Path) -> None:
    _write(tmp_path / "app.py", "print('ok')\n")
    _write(tmp_path / "node_modules" / "pkg" / "index.js", "ignored()\n")
    _write(tmp_path / "dist" / "bundle.js", "ignored()\n")
    _write(tmp_path / "pkg" / "__pycache__" / "cached.py", "ignored()\n")
    _write(tmp_path / "app" / "migrations" / "001_init.py", "ignored()\n")

    result = ingest_repository(tmp_path)

    assert [file.filepath for file in result.files] == ["app.py"]


def test_skips_license_binary_generated_and_large_files(tmp_path: Path) -> None:
    _write(tmp_path / "LICENSE", "MIT\n")
    _write_bytes(tmp_path / "binary.py", b"\x00\x01")
    _write(tmp_path / "generated.py", "# Auto-generated by a tool\nVALUE = 1\n")
    _write(tmp_path / "large.py", "\n".join(f"line_{index} = {index}" for index in range(6)))
    _write(tmp_path / "ok.py", "VALUE = 1\n")

    result = ingest_repository(tmp_path, max_lines=5)

    assert [file.filepath for file in result.files] == ["ok.py"]
    assert {skipped.filepath: skipped.reason for skipped in result.skipped} == {
        "LICENSE": "license",
        "binary.py": "binary_or_non_utf8",
        "generated.py": "generated",
        "large.py": "too_many_lines:6",
    }


def test_write_raw_file_list_outputs_flat_json(tmp_path: Path) -> None:
    _write(tmp_path / "app.py", "print('ok')\n")
    result = ingest_repository(tmp_path)
    output_path = tmp_path / "data" / "raw" / "files.json"

    write_raw_file_list(result.files, output_path)

    assert json.loads(output_path.read_text(encoding="utf-8")) == [
        {"filepath": "app.py", "raw_content": "print('ok')\n"}
    ]


def test_cli_prints_summary(tmp_path: Path) -> None:
    _write(tmp_path / "app.py", "print('ok')\n")

    result = subprocess.run(
        [sys.executable, "-m", "src.ingest", "--repo", str(tmp_path)],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )

    assert "Ingested 1 files" in result.stdout
    assert "Sample file" in result.stdout
    assert "app.py" in result.stdout


def test_cli_json_outputs_raw_file_records(tmp_path: Path) -> None:
    _write(tmp_path / "app.py", "print('ok')\n")

    result = subprocess.run(
        [sys.executable, "-m", "src.ingest", "--repo", str(tmp_path), "--json"],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )

    assert json.loads(result.stdout) == [{"filepath": "app.py", "raw_content": "print('ok')\n"}]


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _write_bytes(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
