"""Repository ingestion for raw source files and README documentation."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Sequence

SUPPORTED_EXTENSIONS = {".py", ".js", ".ts", ".java"}
README_SUFFIXES = {"", ".md", ".rst", ".txt"}
LICENSE_NAMES = {
    "copying",
    "copying.md",
    "copying.txt",
    "license",
    "license.md",
    "license.txt",
    "notice",
    "notice.md",
    "notice.txt",
}
IGNORED_DIRS = {
    ".git",
    ".hg",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "build",
    "coverage",
    "dist",
    "env",
    "migrations",
    "node_modules",
    "site-packages",
    "venv",
}
GENERATED_HEADER_MARKERS = {
    "@generated",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "generated by",
}
GENERATED_NAME_SUFFIXES = {
    ".min.js",
    "_pb2.py",
    "_pb2_grpc.py",
}
DEFAULT_MAX_LINES = 500
DEFAULT_RAW_ROOT = Path("data/raw")


@dataclass(frozen=True)
class RawFile:
    """A repository-relative raw text file ready for chunking."""

    filepath: str
    raw_content: str

    def to_dict(self) -> dict[str, str]:
        """Return a JSON-serializable representation of the raw file."""

        return asdict(self)


@dataclass(frozen=True)
class SkippedFile:
    """A file skipped during ingestion, with a compact reason."""

    filepath: str
    reason: str

    def to_dict(self) -> dict[str, str]:
        """Return a JSON-serializable representation of the skipped file."""

        return asdict(self)


@dataclass(frozen=True)
class IngestionResult:
    """Files collected from a repository and files skipped with reasons."""

    files: list[RawFile]
    skipped: list[SkippedFile]


def ingest_repository(repo: str | Path, max_lines: int = DEFAULT_MAX_LINES) -> IngestionResult:
    """Collect supported source and README files from a local repository path."""

    repo_path = Path(repo).resolve()
    if not repo_path.exists():
        raise FileNotFoundError(f"Repository path does not exist: {repo_path}")
    if not repo_path.is_dir():
        raise NotADirectoryError(f"Repository path is not a directory: {repo_path}")

    files: list[RawFile] = []
    skipped: list[SkippedFile] = []
    for path in _iter_candidate_files(repo_path):
        relative_path = _relative_path(path, repo_path)
        skip_reason = _candidate_skip_reason(path)
        if skip_reason is not None:
            skipped.append(SkippedFile(filepath=relative_path, reason=skip_reason))
            continue

        content = _read_text_or_none(path)
        if content is None:
            skipped.append(SkippedFile(filepath=relative_path, reason="binary_or_non_utf8"))
            continue

        if _looks_generated(path, content):
            skipped.append(SkippedFile(filepath=relative_path, reason="generated"))
            continue

        line_count = len(content.splitlines())
        if line_count > max_lines:
            skipped.append(SkippedFile(filepath=relative_path, reason=f"too_many_lines:{line_count}"))
            continue

        files.append(RawFile(filepath=relative_path, raw_content=content))

    return IngestionResult(files=files, skipped=skipped)


def clone_repository(url: str, dest: str | Path | None = None) -> Path:
    """Clone `url` into `dest` or `data/raw/<repo-name>`, reusing existing clones."""

    from git import Repo

    destination = Path(dest) if dest is not None else DEFAULT_RAW_ROOT / _repo_name_from_url(url)
    destination = destination.resolve()
    if destination.exists():
        if (destination / ".git").exists():
            return destination
        if any(destination.iterdir()):
            raise FileExistsError(f"Destination exists and is not a git repository: {destination}")
    else:
        destination.parent.mkdir(parents=True, exist_ok=True)

    Repo.clone_from(url, destination)
    return destination


def write_raw_file_list(files: Sequence[RawFile], output_path: str | Path) -> None:
    """Persist raw file records as JSON for downstream chunking/indexing steps."""

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = [file.to_dict() for file in files]
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def main(argv: Sequence[str] | None = None) -> int:
    """Run the ingestion CLI for a local repository or a git URL."""

    parser = argparse.ArgumentParser(description="Ingest supported source files from a repository.")
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--repo", help="Local repository path to crawl.")
    source.add_argument("--url", help="Git URL to clone before crawling.")
    parser.add_argument("--dest", help="Clone destination for --url. Defaults to data/raw/<repo-name>.")
    parser.add_argument("--max-lines", type=int, default=DEFAULT_MAX_LINES, help="Skip files over this line count.")
    parser.add_argument("--output", help="Optional JSON path for the flat raw file list.")
    parser.add_argument("--json", action="store_true", help="Emit raw file records as JSON.")
    args = parser.parse_args(argv)

    repo_path = clone_repository(args.url, args.dest) if args.url else Path(args.repo).resolve()
    result = ingest_repository(repo_path, max_lines=args.max_lines)

    if args.output:
        write_raw_file_list(result.files, args.output)

    if args.json:
        print(json.dumps([file.to_dict() for file in result.files], indent=2))
        return 0

    print(f"Ingested {len(result.files)} files from {repo_path}")
    print(f"Skipped {len(result.skipped)} files")
    for reason, count in sorted(Counter(skipped.reason for skipped in result.skipped).items()):
        print(f"  {reason}: {count}")
    if args.output:
        print(f"Wrote raw file list to {args.output}")
    if result.files:
        sample = result.files[0]
        print()
        print("Sample file")
        print(f"  filepath: {sample.filepath}")
        print(f"  lines: {len(sample.raw_content.splitlines())}")
    return 0


def _iter_candidate_files(root: Path) -> list[Path]:
    files: list[Path] = []
    stack = [root]
    while stack:
        current = stack.pop()
        for child in sorted(current.iterdir(), key=lambda path: path.name):
            if child.is_dir():
                if child.name not in IGNORED_DIRS:
                    stack.append(child)
            elif child.is_file():
                files.append(child)
    return sorted(files)


def _candidate_skip_reason(path: Path) -> str | None:
    name = path.name.lower()
    if name in LICENSE_NAMES:
        return "license"
    if _is_readme(path) or path.suffix.lower() in SUPPORTED_EXTENSIONS:
        return None
    return "unsupported_type"


def _is_readme(path: Path) -> bool:
    return path.stem.lower() == "readme" and path.suffix.lower() in README_SUFFIXES


def _read_text_or_none(path: Path) -> str | None:
    data = path.read_bytes()
    if b"\x00" in data:
        return None
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:
        return None


def _looks_generated(path: Path, content: str) -> bool:
    lower_name = path.name.lower()
    if any(lower_name.endswith(suffix) for suffix in GENERATED_NAME_SUFFIXES):
        return True

    header = "\n".join(content.splitlines()[:20]).lower()
    return any(marker in header for marker in GENERATED_HEADER_MARKERS)


def _relative_path(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def _repo_name_from_url(url: str) -> str:
    name = Path(url.rstrip("/").removesuffix(".git")).name
    return name or "repository"


if __name__ == "__main__":
    raise SystemExit(main())
